### ISSUE TITLE
French better translation + fix of a bug on translation

### ISSUE THREAD

**Issue by Telepathique** [serjoscha87/HintMeRank#2]
![betteroutdated](https://github.com/serjoscha87/HintMeRank/assets/30240088/c099732f-6401-406a-a6f5-cb12d1a745f2)
![fading fixed](https://github.com/serjoscha87/HintMeRank/assets/30240088/46bd17c8-2101-4cb5-8437-2b031a84f1f0)
@serjoscha87 @bassauer-storms-media sorry for the tag but i Updated my translation since i found issue on it.
Changelog ;
-Fixed fading that was not appearing
-Changed some wording for a better french translation of the usage 

just replace the fr.lua content to :
`-- thanks to Chassemoss from Auberdine for the translation!

if GetLocale() == "frFR" then
i18n = {
["all spells on max rank"] = "Tous les sorts sur vos barres d'action sont au rang maximum !",
["uprank failed because spell not learned"] = "|cffFF0000Ce sort ne peut pas être amélioré car vous n'avez pas encore appris le nouveau rang. Veuillez consulter un entraineur et réessayer.|r",
["uprank successful"] = "%s |cffFF0000%s|r amélioré avec succès vers %s |cff00FF00%s|r!",
["outranked spell used chat"] = " Utilisation de %s |cffFF0000%s|r détecté.\nUn rang suppérieur est disponible pour votre |cffFF0000niveau %d|r c'est:\n%s |cffFF0000%s|r!",
["outranked spell used fading"] = "Utilisation de %s |cffFF0000%s|r Détecté.\nAmélioration disponible: |cffFF0000niveau %d|r vers le |cffFF0000%s|r!",
["info row chunks"] = {
"peu être amélioré vers",
"",
"AMELIORER",
"APPRENDRE"
},
["uprank all"] = "Améliorer tout"
}
end`
Cordially Chassemoss

**Comment by bassauer-storms-media** [comment]
updated the FR translations.

could you perhaps set up a pull request next time? this would make things way easier for me :)

cheers

**Comment by serjoscha87** [comment]
updated the FR translations (may take a while until curseforge publishs the new version).

could you perhaps set up a pull request next time? this would make things way easier for me :)

cheers
